### ISSUE TITLE
Fix welcome message

### ISSUE THREAD

**Issue by omarkhs** [QMuncaster/RxOn#23]
welcome message is reactive to user first name and last name: presently says "welcome undefined undefined" until the server responds with the account's names. 

Would be good to instead prevent welcome message from rendering until a user a logged in.

**Comment by QMuncaster** [comment]
this was trivial so I just fixed it directly into project_5 branch:
https://github.com/QMuncaster/RxOn/blob/07b25291b999cbf5c69189049c4a46ebcba49bfb/RxOn/imports/ui/Navbar.js#L34

**Comment by omarkhs** [comment]
Sounds good! thanks
