### ISSUE TITLE
Clean up date formats

### ISSUE THREAD

**Issue by omarkhs** [QMuncaster/RxOn#24]
clean up date formats, i.e. instead of showing "Sat Jul 06 2019 21:55:35 GMT-0700 (Pacific Daylight Time)" show "July 06 2019" or similar

**Comment by QMuncaster** [comment]
this was trivial so I just fixed it directly into project_5 branch:
https://github.com/QMuncaster/RxOn/blob/a88914b47cded17c95626a328b0899038a15a0e8/RxOn/imports/ui/patient_components/PatientPrescription.js#L21

**Comment by omarkhs** [comment]
@QMuncaster Thank you 😃
