### ISSUE TITLE
fade out login and create account buttons

### ISSUE THREAD

**Issue by QMuncaster** [QMuncaster/RxOn#36]
the buttons should become grey and unclickable until the server responds, e.g. during the lag here:
![output](https://user-images.githubusercontent.com/12143900/60843717-4d8b9f00-a18c-11e9-80b4-9690bac4ce0c.gif)

I would start with the login button as login page already uses redux-forms

can probably reference a react state as done here:
https://github.com/QMuncaster/RxOn/blob/07b25291b999cbf5c69189049c4a46ebcba49bfb/RxOn/imports/ui/SignupPage.js#L14

maybe after we implement greying out the button, we can get rid of the referenced check in the link above

**Comment by omarkhs** [comment]
we can also do a login spinner..or as Quintin said just grey out the button and change text to "loading..." (this is just styling) but we will need to have something to prevent triggering of actions or a flag called clickable for example and set it to false upon submit to stop clicking action or we can use redux. There are several options. @costewart let me know if you need any help!

**Comment by QMuncaster** [comment]
Check out the create account code, we can use a lock that prevents someone
from making another request until first one finishes.

This might be simple enough to use with the lock ^^:
https://stackoverflow.com/questions/13831601/disabling-and-enabling-a-html-input-button/13831737
